### ISSUE TITLE
Not compatible with 2019 version

### ISSUE THREAD

**Issue by vlebourl** [EddieRingle/clion-cmakedocs#5]
First 2019 EAPs are out. Any plan to update the plugin?

**Comment by heretyk999** [comment]
Quick fix to compatibility with CLion 2019.1 and AsciiDoc 0.24 is available in my pull request: #6

**Comment by EddieRingle** [comment]
Thanks @WaruiOkami, I'll try to get that merged in soon.

**Comment by vlebourl** [comment]
any news?

**Comment by airfield20** [comment]
Also doesnt work in 2020 version

**Comment by YowFung** [comment]
Also doesn't work in 2021 version

**Comment by Ayfri** [comment]
Same in 2022

**Comment by EddieRingle** [comment]
Sorry this was left to gather dust, all.[ CLion 2022.2 now includes this functionality by default](https://blog.jetbrains.com/clion/2022/07/clion-2022-2/#quick_documentation), so I'm archiving the repository.
